compiler:
    - gcc

os:
    - linux

before_script:
    ./autogen.sh

language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libglib2.0-dev
            - libcurl4-openssl-dev
            - gcc-5
            - valgrind
            - autoconf 
            - automake


script:
    - ./configure && make && make check && make distcheck 


