compiler:
    - gcc

os:
    - linux

before_script:
    ./autogen.sh

language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - glib-dev
            - libcurl-dev
            - gcc-5
            - valgrind


script:
    - ./configure && make && make check && make distcheck 


